01_standard
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 00_4E, debug: false, detectionLogName: 00_4E_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 00_4E_flow_log,
  flowModelName: 00_4E_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0, flowWeightZ: 1.0,
  learningRate: 0.01, logFileName: 00_4E.log, logInterval: 1, maxDisplacement: 80.0,
  maxRadius: 5.0, medianCorrection: false, minRadius: 1.0, name: 00_4E,
  numCrops: 50, numEpochs: 10, outputPrediction: false, pad: true, patch: false, patchSizeX: 384,
  patchSizeY: 384, patchSizeZ: 15, probThreshold: 0.7, rescaleX: 1.0, rescaleY: 1.0,
  rescaleZ: 1.0, suppressionDistance: 3.0, timeRange: 55, trainingCropSizeX: 128,
  trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false, useInterpolation: false,
  useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 01_standard, debug: false, detectionLogName: 01_standard_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 01_standard_flow_log,
  flowModelName: 01_standard_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 01_standard.log, logInterval: 1,
  maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false, minRadius: 1.0,
  name: 01_standard, numCrops: 100, numEpochs: 10, outputPrediction: false,
  pad: true, patch: false, patchSizeX: 384, patchSizeY: 384, patchSizeZ: 8, probThreshold: 0.7,
  rescaleX: 1.0, rescaleY: 1.0, rescaleZ: 2.0, suppressionDistance: 3.0, timeRange: 28,
  trainingCropSizeX: 128, trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false,
  useInterpolation: false, useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 01_standard_deconvolution, debug: false, detectionLogName: 01_standard_deconvolution_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 01_standard_deconvolution_flow_log,
  flowModelName: 01_standard_deconvolution_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0, flowWeightZ: 1.0,
  learningRate: 0.01, logFileName: 01_standard_deconvolution.log, logInterval: 1, maxDisplacement: 80.0,
  maxRadius: 5.0, medianCorrection: false, minRadius: 1.0, name: 01_standard_deconvolution,
  numCrops: 50, numEpochs: 10, outputPrediction: false, pad: true, patch: false, patchSizeX: 384,
  patchSizeY: 384, patchSizeZ: 15, probThreshold: 0.7, rescaleX: 1.0, rescaleY: 1.0,
  rescaleZ: 1.0, suppressionDistance: 3.0, timeRange: 55, trainingCropSizeX: 128,
  trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false, useInterpolation: false,
  useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 01_standard_denoising_n2v, debug: false, detectionLogName: 01_standard_denoising_n2v_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 01_standard_denoising_n2v_flow_log,
  flowModelName: 01_standard_denoising_n2v_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 01_standard_denoising_n2v.log,
  logInterval: 1, maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false,
  minRadius: 1.0, name: 01_standard_denoising_n2v, numCrops: 100, numEpochs: 10,
  outputPrediction: false, pad: true, patch: false, patchSizeX: 384, patchSizeY: 384,
  patchSizeZ: 8, probThreshold: 0.7, rescaleX: 1.0, rescaleY: 1.0, rescaleZ: 2.0,
  suppressionDistance: 3.0, timeRange: 28, trainingCropSizeX: 128, trainingCropSizeY: 128,
  trainingCropSizeZ: 16, use2dModel: false, useInterpolation: false, useMemmap: false,
  useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 02_improved_z, debug: false, detectionLogName: 02_improved_z_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 02_improved_z_flow_log,
  flowModelName: 02_improved_z_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 02_improved_z.log,
  logInterval: 1, maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false,
  minRadius: 1.0, name: 02_improved_z, numCrops: 100, numEpochs: 10, outputPrediction: false,
  pad: true, patch: false, patchSizeX: 384, patchSizeY: 384, patchSizeZ: 15, probThreshold: 0.7,
  rescaleX: 1.0, rescaleY: 1.0, rescaleZ: 1.0, suppressionDistance: 3.0, timeRange: 28,
  trainingCropSizeX: 128, trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false,
  useInterpolation: false, useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 03_improved_t, debug: false, detectionLogName: 03_improved_t_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 03_improved_t_flow_log,
  flowModelName: 03_improved_t_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 03_improved_t.log,
  logInterval: 1, maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false,
  minRadius: 1.0, name: 03_improved_t, numCrops: 50, numEpochs: 10, outputPrediction: false,
  pad: true, patch: false, patchSizeX: 384, patchSizeY: 384, patchSizeZ: 8, probThreshold: 0.7,
  rescaleX: 1.0, rescaleY: 1.0, rescaleZ: 2.0, suppressionDistance: 3.0, timeRange: 55,
  trainingCropSizeX: 128, trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false,
  useInterpolation: false, useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 04_improved_zt1, debug: false, detectionLogName: 04_improved_zt1_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 04_improved_zt1_flow_log,
  flowModelName: 04_improved_zt1_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 04_improved_zt1.log,
  logInterval: 1, maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false,
  minRadius: 1.0, name: 04_improved_zt1, numCrops: 50, numEpochs: 10, outputPrediction: false,
  pad: true, patch: false, patchSizeX: 384, patchSizeY: 384, patchSizeZ: 15, probThreshold: 0.7,
  rescaleX: 2.0, rescaleY: 2.0, rescaleZ: 1.0, suppressionDistance: 3.0, timeRange: 55,
  trainingCropSizeX: 128, trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false,
  useInterpolation: false, useMemmap: false, useOpticalflow: false}
--- !!org.elephant.setting.main.ElephantMainSettings {NNLinkingThreshold: 5.0, NNMaxEdges: 1,
  NNSearchDepth: 1, NNSearchNeighbors: 3, augContrast: 0.0, augRotationAngle: 0.0,
  augScaleFactorBase: 0.0, autoBgThreshold: 0.0, batchSize: 20, cacheMaxbytesMebi: 10240,
  centerRatio: 0.4, classWeightBG: 1.0, classWeightBorder: 10.0, classWeightCenter: 10.0,
  datasetName: 05_improved_zt2, debug: false, detectionLogName: 05_improved_zt2_detection_log,
  detectionModelName: versatile3d_detection.pth, falseWeight: 10.0, flowLogName: 05_improved_zt2_flow_log,
  flowModelName: 05_improved_zt2_flow.pth, flowWeightX: 1.0, flowWeightY: 1.0,
  flowWeightZ: 1.0, learningRate: 0.01, logFileName: 05_improved_zt2.log,
  logInterval: 1, maxDisplacement: 80.0, maxRadius: 5.0, medianCorrection: false,
  minRadius: 1.0, name: 05_improved_zt2, numCrops: 50, numEpochs: 10, outputPrediction: false,
  pad: true, patch: false, patchSizeX: 384, patchSizeY: 384, patchSizeZ: 15, probThreshold: 0.7,
  rescaleX: 1.0, rescaleY: 1.0, rescaleZ: 1.0, suppressionDistance: 3.0, timeRange: 55,
  trainingCropSizeX: 128, trainingCropSizeY: 128, trainingCropSizeZ: 16, use2dModel: false,
  useInterpolation: false, useMemmap: false, useOpticalflow: false}